#!/bin/bash
echo "-----------------------------------"
echo "updateall for Debian & Ubuntu"
echo "-----------------------------------"

#Run this as a normal user. Your admin password will be asked for if required.

# Standard error mitigation

set -euo pipefail

# The first bit is the standard apt stuff

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get full-upgrade -y
sudo apt-get autoremove -y

# This will get rid of any old kernels. It requires Byobu to be installed.

sudo purge-old-kernels -y

# Uncomment if you care about snaps being bang up to date

# sudo snap refresh

# Uncomment if you are using Flatpaks and you want them to be updated by this script

# flatpak update -y

# These commands are specific to any computer set up using any of my deployment scripts
# They will start, update and then stop the containers created as part of that script
# If you keep the containers running all the time then comment out the relevant lines

# multipass start ubuntu-lts
# multipass exec ubuntu-lts updateall
# multipass stop ubuntu-lts

echo "The script has now finished running."
